version: '3.9'

services:
  web:
    build: .
    command: gunicorn forum-sandbox.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/forum-sandbox
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      # POSTGRES_INITDB_ARGS: "--username=${PG_USER}" 
      #PGDATABASE: ${PG_DB}
     # PGPASSWORD: ${PG_PASSWORD}
      #PGUSER: ${PG_USER}
    ports:
      - ${DB_PORT_OUT}:5432
  pgadmin4:
    container_name: forum-sandbox_pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin/data
volumes:
  db_data:
  pgadmin-data: