version: '3.9'

services:
  web:
    build: .
    command: gunicorn forum-sandbox.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./:/forum-sandbox
      - ./logs:/logs
    ports:
      - 8000:8000
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14
    restart: always
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./forum_d.sql:/docker-entrypoint-initdb.d/forum_d.sql
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
    ports:
      - ${DB_PORT_OUT}:5432
volumes:
  db_data:
  pgadmin-data:
  logs:
